server:
  port: ${PORT:8081}

logging:
  level:
    oxyac.shopping: ${LOG_LEVEL:ERROR}

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
  datasource:
    url: jdbc:h2:${H2_DB_PATH:mem:crm}
    driverClassName: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true

